name: CI

on:
  pull_request:
    branches:
      - dev
      - main

  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
      NEXT_PUBLIC_APP_DOMAIN: ${{ vars.NEXT_PUBLIC_APP_DOMAIN }}

      NEXT_PUBLIC_SIGNUP_EMAIL_REDIRECT_TO: ${{vars.NEXT_PUBLIC_SIGNUP_EMAIL_REDIRECT_TO}}
      NEXT_PUBLIC_PASSWORD_RESET_EMAIL_REDIRECT_TO: ${{vars.NEXT_PUBLIC_PASSWORD_RESET_EMAIL_REDIRECT_TO}}
      NEXT_PUBLIC_OAUTH_EMAIL_REDIRECT_TO: ${{vars.NEXT_PUBLIC_OAUTH_EMAIL_REDIRECT_TO}}
      NEXT_PUBLIC_COOLDOWN_SECONDS: ${{vars.NEXT_PUBLIC_COOLDOWN_SECONDS}}

      RAZORPAY_KEY_ID: ${{ vars.RAZORPAY_KEY_ID }}
      RAZORPAY_KEY_SECRET: ${{ secrets.RAZORPAY_KEY_SECRET }}
      RAZORPAY_WEBHOOK_SECRET: ${{ secrets.RAZORPAY_WEBHOOK_SECRET }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Type Check
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Production Build
        run: npm run build
